FROM myrotvorets/node:latest@sha256:a78ed3a145d0c46766612491823f44f11f944a83ef2a74a63214de9ed017262a AS base
ARG GPR_AUTH_TOKEN
USER root
WORKDIR /srv/service
RUN chown nobody:nogroup /srv/service
USER nobody:nogroup
COPY --chown=nobody:nogroup ./package.json ./package-lock.json ./tsconfig.json .npmrc ./
RUN \
    echo '//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' >> .npmrc && \
    NODE_AUTH_TOKEN="${GPR_AUTH_TOKEN}" npm ci --ignore-scripts && \
    NODE_AUTH_TOKEN= npm rebuild && \
    NODE_AUTH_TOKEN= npm run prepare --if-present
COPY --chown=nobody:nogroup ./ ./
ENTRYPOINT ["/usr/bin/npm", "run", "ci"]
