FROM myrotvorets/node:latest@sha256:1de8cb98ba63a6e3dd5ce5eea9cbcb58d4d39a0afbdddad457ba4fe6eff94922
USER root
WORKDIR /srv/service
RUN chown nobody:nobody /srv/service
USER nobody:nobody
COPY --chown=nobody:nobody ./package.json ./package-lock.json ./tsconfig.json .npmrc* ./
RUN \
    npm ci --ignore-scripts --userconfig .npmrc.local && \
    npm rebuild && \
    npm run prepare --if-present
COPY --chown=nobody:nobody ./ ./
RUN mkdir dist
