FROM myrotvorets/node:latest@sha256:71f5835c89808033ff8ee5d30a4f1fb50157c18f94ea1bf83d617da228383a0a
USER root
WORKDIR /srv/service
RUN chown nobody:nobody /srv/service
USER nobody:nobody
COPY --chown=nobody:nobody ./package.json ./package-lock.json ./tsconfig.json .npmrc* ./
RUN \
    npm ci --ignore-scripts --userconfig .npmrc.local && \
    npm rebuild && \
    npm run prepare --if-present
COPY --chown=nobody:nobody ./ ./
RUN mkdir dist
