FROM myrotvorets/node:latest@sha256:95168eb87ee2a1f75c7706e2b787e7aec592f28d515bc36401129c0587114e02 AS base
ARG GPR_AUTH_TOKEN
USER root
WORKDIR /srv/service
RUN chown nobody:nogroup /srv/service
USER nobody:nogroup
COPY --chown=nobody:nogroup ./package.json ./package-lock.json ./tsconfig.json .npmrc ./
RUN \
    echo '//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' >> .npmrc && \
    NODE_AUTH_TOKEN="${GPR_AUTH_TOKEN}" npm ci --ignore-scripts && \
    NODE_AUTH_TOKEN= npm rebuild && \
    NODE_AUTH_TOKEN= npm run prepare --if-present
COPY --chown=nobody:nogroup ./ ./
ENTRYPOINT ["/usr/bin/npm", "run", "ci"]
