FROM myrotvorets/node:latest@sha256:48536a7d982cf0f6c6ca5ddb26169bf56d2a4182fa1cef09f079beb7bc747b17
USER root
WORKDIR /srv/service
RUN chown nobody:nobody /srv/service
USER nobody:nobody
COPY --chown=nobody:nobody ./package.json ./package-lock.json ./tsconfig.json .npmrc* ./
RUN \
    npm ci --ignore-scripts --userconfig .npmrc.local && \
    npm rebuild && \
    npm run prepare --if-present
COPY --chown=nobody:nobody ./ ./
RUN mkdir dist
