name: Integration Testing

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Integration Testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: true

      - name: Create coverage directory
        run: install -d coverage -m 0777

      - name: Set up auth token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc.local

      - name: Run tests
        run: docker compose -f docker-compose-ci.yml up --build --abort-on-container-exit --renew-anon-volumes

      - name: Run codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
        with:
          flags: integration-tests
